export default {
  doLogin: '/api/login',
  getByMonth: '/api/takeList',
  getByTime: '/api/takes/searched',
  getDataSave: '/api/takes/export',
  getTotal: '/api/count-total',
  getMonthData: '/api/result-month',
  getDataTable: '/api/count-contestant-month',
  getStatisticByMonth: '/api/inforcontestantsbyor',
  getTotalFailed: '/api/totalViolation',
  getUserByOrganization: '/api/user/organization',
  getOrganization: '/api/organization/result',
  getContetstByUid: '/api/contests/user',
  getDetailResult: '/api/results',
  getEssayInfo: '/api/search-essay-by-user',
  viewEssay: 'api/view-essay',
  exportExcel: 'api/export',
  searchExam: '/api/search-exam-round',
  searchContest: '/api/search-contest',
  exportResultByName: '/api/export/results/all',
  getContestant: '/api/list-total',
};
export const apiUrl = 'https://62b895e2366a.ngrok.io/';
